services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: skill_bridge_backend_user
      POSTGRES_PASSWORD: skill_bridge_backend_password
      POSTGRES_DB: skill_bridge_backend_db
    ports:
      - "5434:5432"
    networks:
      - skill_bridge_backend_network
networks:
  skill_bridge_backend_network:
    driver: bridge
