services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Default DATABASE_URL points to the postgres service inside the compose network.
      # If you deploy to a platform (Render, Railway), set DATABASE_URL in the platform env vars
      - DATABASE_URL=${DATABASE_URL:-postgresql://skill_bridge_backend_user:skill_bridge_backend_password@postgres:5432/skill_bridge_backend_db}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - skill_bridge_backend_network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: skill_bridge_backend_user
      POSTGRES_PASSWORD: skill_bridge_backend_password
      POSTGRES_DB: skill_bridge_backend_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skill_bridge_backend_network

volumes:
  postgres_data:

networks:
  skill_bridge_backend_network:
    driver: bridge
